name: 'Maybe Create Repo'
description: 'Ensure that a repo exists'
inputs:
  token:  # id of input
    description: 'GH Token'
    required: false
    default: "${{ github.token }}"
  repo:  
    description: 'GH Repo Check'
    required: false
    default: "${{ github.repository }}"
  repo-suffix:  
    description: 'Suffix'
    required: false
    default: "built"
runs:
  using: 'node16'
  main: 'main.js'
